CREATE TABLE DEPARTMENTS (DEPT_ID INT PRIMARY KEY, DEPT_NAME VARCHAR(50));

CREATE TABLE EMPLOYEES (
	EMP_ID INT PRIMARY KEY,
	EMP_NAME VARCHAR(50),
	DEPT_ID INT,
	SALARY INT,
	FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS (DEPT_ID)
);

INSERT INTO
	DEPARTMENTS (DEPT_ID, DEPT_NAME)
VALUES
	(1, 'HR'),
	(2, 'IT'),
	(3, 'Finance'),
	(4, 'Marketing');

INSERT INTO
	EMPLOYEES (EMP_ID, EMP_NAME, DEPT_ID, SALARY)
VALUES
	(101, 'Amit', 1, 40000),
	(102, 'Neha', 2, 60000),
	(103, 'Rahul', 2, 55000),
	(104, 'Pooja', 3, 50000),
	(105, 'Karan', 4, 45000);

SELECT
	*
FROM
	EMPLOYEES
SELECT
	*
FROM
	DEPARTMENTS
INSERT INTO
	EMPLOYEES
VALUES
	(106, 'Raj', 2, 70000)
INSERT INTO
	EMPLOYEES (EMP_ID, EMP_NAME, SALARY)
VALUES
VALUES
	(107, 'Meet', 45000)
	-- Display employee name with department name
SELECT
	EMP_NAME AS EMPLOYEE,
	DEPT_NAME AS DEPARTMENT
FROM
	EMPLOYEES E
	JOIN DEPARTMENTS D ON E.DEPT_ID = D.DEPT_ID
	-- Display employees earning more than 50,000 
SELECT
	EMP_NAME AS EMPLOYEE,
	DEPT_NAME AS DEPARTMENT,
	SALARY
FROM
	EMPLOYEES E
	JOIN DEPARTMENTS D ON E.DEPT_ID = D.DEPT_ID
WHERE
	SALARY > 50000
	-- Display department-wise total salary
SELECT
	DEPT_NAME AS DEPARTMENT,
	SUM(SALARY) AS TOTAL_SALARY
FROM
	EMPLOYEES E
	JOIN DEPARTMENTS D ON E.DEPT_ID = D.DEPT_ID
GROUP BY
	D.DEPT_NAME
	-- Display departments with more than 2 employees
SELECT
	DEPT_NAME AS DEPARTMENT,
	COUNT(*) AS TOTAL_EMP
FROM
	DEPARTMENTS D
	JOIN EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
GROUP BY
	DEPT_NAME
HAVING
	COUNT(*) > 2
	--Display employees without a department
SELECT
	E.EMP_ID,
	E.EMP_NAME,
	D.DEPT_NAME,
	E.SALARY
FROM
	EMPLOYEES E
	LEFT JOIN DEPARTMENTS D ON E.DEPT_ID = D.DEPT_ID
WHERE
	D.DEPT_ID IS NULL;


